CREATE TABLE IF NOT EXISTS islands(id TEXT PRIMARY KEY, name TEXT NOT NULL);
INSERT OR IGNORE INTO islands VALUES('muli','Muli');
CREATE TABLE IF NOT EXISTS locations(id TEXT PRIMARY KEY, island TEXT NOT NULL REFERENCES islands(id), name TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS drivers(id TEXT PRIMARY KEY, island TEXT NOT NULL REFERENCES islands(id), name TEXT NOT NULL, phone TEXT NOT NULL, taxi TEXT, pin_hash TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1, online INTEGER NOT NULL DEFAULT 0, created INTEGER NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS drivers_phone ON drivers(island, phone);
CREATE TABLE IF NOT EXISTS bookings(id TEXT PRIMARY KEY, island TEXT NOT NULL REFERENCES islands(id), name TEXT NOT NULL, phone TEXT NOT NULL, pickup TEXT NOT NULL, dest TEXT NOT NULL, pax TEXT NOT NULL, when_type TEXT NOT NULL, date TEXT, time TEXT, price REAL NOT NULL DEFAULT 0, pay TEXT NOT NULL DEFAULT 'cash', status TEXT NOT NULL DEFAULT 'NEW', driver_id TEXT REFERENCES drivers(id), created INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS bookings_status ON bookings(island, status, created);
CREATE TABLE IF NOT EXISTS settings(island TEXT PRIMARY KEY REFERENCES islands(id), json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS rl(k TEXT PRIMARY KEY, n INTEGER NOT NULL, t INTEGER NOT NULL);
